# This is a basic workflow to help you get started with Actions

name: Create branch

# Controls when the workflow will run
on:
  schedule:
   - cron: "*/5 * * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create_branch:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
          fetch-depth: 0

      - name: 'github.sha 1'
        run: echo "github.sha#${{ github.sha }}"    

      - name: 'Get dev SHA'
        run: echo "SHA=$(/usr/bin/git log -1 --format=%H)" >> $GITHUB_ENV

      - name: 'print SHA'
        run: echo $SHA
        
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: 'Next version'
        run: echo "Creating branch refs/heads/release/${{ steps.semvers.outputs.minor }}"
      
      - name: 'github.sha 2'
        run: echo "github.sha#${{ github.sha }}"
        
        
      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "refs/heads/release/${{ steps.semvers.outputs.minor }}"
          sha: $(/usr/bin/git log -1 --format=%H)
