# This is a basic workflow to help you get started with Actions

name: Create branch

# Controls when the workflow will run
on:
  schedule:
   - cron: '0 22 25 10 *'
   - cron: '47 22 25 10 *'
   - cron: '10 01 26 10 *'
   - cron: '50 01 26 10 *'
   - cron: '55 01 26 10 *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create_branch:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
          fetch-depth: 0

      - name: 'Get base branch SHA'
        run: echo "SHA=$(/usr/bin/git log -1 --format=%H)" >> $GITHUB_ENV
        
      - name: 'Get previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: 'Set branch name'
        run: |
         BRANCH_NAME=${{ steps.semvers.outputs.minor }}
         echo "BRANCH_NAME=${BRANCH_NAME//.0/.x}" >> $GITHUB_ENV
        
      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "refs/heads/release/${{ env.BRANCH_NAME }}"
          sha: ${{ env.SHA }}
