# This is a basic workflow to help you get started with Actions

name: Create branch

# Controls when the workflow will run
on:
  schedule:
   - cron: "20 16 * * *"
   - cron: "25 16 * * *"
   - cron: "30 16 * * *"
   - cron: "35 16 * * *"
   - cron: "40 16 * * *"
   - cron: "45 16 * * *"
   - cron: "20 19 * * *"
   - cron: "25 19 * * *"
   - cron: "30 19 * * *"
   - cron: "35 19 * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  create_branch:
    permissions: write-all
    runs-on: ubuntu-latest

    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
          fetch-depth: 0
          
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: 'Next version'
        run: echo "Creating branch refs/heads/release/${{ steps.semvers.outputs.minor }}"

      - name: 'GITHUB_SHA'
        run: echo "GITHUB_SHA#${{ GITHUB_SHA }}"
      
      - name: 'github.sha'
        run: echo "github.sha#${{ github.sha }}"
        
        
      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "refs/heads/release/${{ steps.semvers.outputs.minor }}"
          sha: ${{ GITHUB_SHA }}
