# This is a basic workflow to help you get started with Actions

name: Create branch

# Controls when the workflow will run
on:
  schedule:
   - cron: "30 22 * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create_branch:
    runs-on: ubuntu-latest

    
    steps:
      - uses: actions/checkout@v1
      
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: 'Exibe próxima versão'
        uses: echo "refs/heads/release/${{ steps.semvers.outputs.minor }}"
        
      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "refs/heads/release/${{ steps.semvers.outputs.minor }}"
